# Generated by Django 2.2.5 on 2019-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ハンドルネーム')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='電話番号')),
                ('gender', models.CharField(blank=True, choices=[('1', '女性'), ('2', '男性')], max_length=2, verbose_name='性別')),
            ],
        ),
    ]
