# Generated by Django 2.2.5 on 2019-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190905_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ニックネーム'),
        ),
    ]
