# Generated by Django 2.2.5 on 2019-09-05 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20190905_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, max_length=50, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='トップ画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.CharField(blank=True, max_length=500, verbose_name='ポートフォリオ'),
        ),
        migrations.AddField(
            model_name='user',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=500, verbose_name='自己PR'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='ニックネーム'),
        ),
    ]
